apiVersion: v1
kind: Service
metadata:
  labels:
    # For use as a Cluster add-on (https://github.com/kubernetes/kubernetes/tree/master/cluster/addons)
    # If you are NOT using this as an addon, you should comment out this line.
    kubernetes.io/cluster-service: 'true'
    kubernetes.io/name: tiller-deploy
  name: tiller-deploy
  namespace: kube-system
spec:
  ports:
  - port: 44134
    targetPort: 44134
  selector:
    app: helm
    name: tiller
