.catalog:
  name: Kubernetes
  version: v1.6.2-rancher3-4
  description: Rancher Kubernetes service
  minimum_rancher_version: v1.6.0-alpha1
  upgrade_from: 0.0.0
  questions:
  - variable: CLOUD_PROVIDER
    label: Cloud Provider
    description: The cloud provider on which Kubernetes is running
    required: true
    default: rancher
    type: enum
    options:
     - rancher
     - aws
  - variable: RBAC
    label: Kubernetes RBAC
    required: true
    default: false
    type: boolean
  - variable: REGISTRY
    description: The registry to pull addon images and the optional pod infra container image. This should be set to the private registry from which the images for addon-services (i.e. helm, heapster, dashboard, dns) and the pod infra container image should be pulled.
    label: Private Registry for Add-Ons and Pod Infra Container Image
    required: false
    default: ""
    type: string
  - variable: ENABLE_RANCHER_INGRESS_CONTROLLER
    description: Deploy the Rancher ingress controller which automatically provisions Rancher load balancers in response to Kubernetes ingress creation events.
    label: Enable Rancher Ingress Controller
    required: true
    default: true
    type: boolean
  - variable: ENABLE_ADDONS
    label: Enable Kubernetes Add-ons
    description: Setting this to `false` will disable Dashboard, Helm, SkyDNS, and other Kubernetes add-on services. This is meant for advanced users who want to deploy custom versions of these add-ons.
    required: true
    default: true
    type: boolean
  - variable: POD_INFRA_CONTAINER_IMAGE
    label: Pod Infra Container Image
    description: The image whose network/ipc namespaces containers in each pod will use. It uses kubelet default if left empty. Do not add the private registry to this field, update the `Private Registry for Add-Ons and Pod Infra Container Image` field with the registry information.
    required: false
    default: "gcr.io/google_containers/pause-amd64:3.0"
    type: string
  - variable: INFLUXDB_HOST_PATH
    label: InfluxDB Host Path
    description: "Write Heapster metrics to an absolute path on the host. This may be network-attached storage."
    required: false
    type: string

  - variable: ANALYTICS
    label: Google Analytics
    description: Send analytical events to Google
    required: true
    default: true
    type: boolean
  - variable: SIZE
    label: Size
    description: Number of Etcd members to create
    required: true
    default: 3
    type: int
  - variable: ENABLE_BACKUPS
    label: Enable Backups
    description: Periodically create backups. Enables automatic disaster recovery except for self-hosted clusters.
    default: true
    type: boolean
  - variable: STORAGE_DRIVER
    label: Storage Driver
    description: If using PersistentVolume storage type, specify the driver to use.
    required: false
    default: rancher-nfs
    type: enum
    options:
    - rancher-efs
    - rancher-nfs
  - variable: BACKUP_INTERVAL
    label: Backup Interval
    description: The interval between two backups.
    required: true
    default: 45m0s
    type: string
  - variable: BACKUP_COUNT
    label: Backup Count
    description: Maximum number of backups to retain. Setting to 0 disables backups and will be unable to recover from majority loss.
    required: true
    default: 32
    type: int
  - variable: CLEANUP_BACKUPS_ON_DELETE
    label: Cleanup Backups
    description: Delete backups when the cluster is deleted.
    default: false
    type: boolean
  - variable: RESTORE_FROM
    label: Restore Cluster
    description: "Restore a cluster by service name or id. Example: etcd-1s42"
    required: false
    type: string
  - variable: ETCD_HEARTBEAT_INTERVAL
    label: Etcd Heartbeat Interval
    description: Time (in milliseconds) of a heartbeat interval.
    required: true
    default: 500
    type: int
  - variable: ETCD_ELECTION_TIMEOUT
    label: Etcd Election Timeout
    description: Time (in milliseconds) for an election to timeout.
    required: true
    default: 5000
    type: int

kubernetes:
    metadata:
        sans:
        - "IP:10.43.0.1"
    health_check:
        request_line: GET /healthz HTTP/1.0
        port: 80
        interval: 2000
        response_timeout: 2000
        unhealthy_threshold: 3
        healthy_threshold: 2
        initializing_timeout: 60000
        reinitializing_timeout: 60000
    retain_ip: true

rancher-kubernetes-agent:
    health_check:
        request_line: GET /healthcheck HTTP/1.0
        port: 10240
        interval: 2000
        response_timeout: 2000
        unhealthy_threshold: 3
        healthy_threshold: 2
        initializing_timeout: 60000
        reinitializing_timeout: 60000

scheduler:
    health_check:
        request_line: GET /healthz HTTP/1.0
        port: 10251
        interval: 2000
        response_timeout: 2000
        unhealthy_threshold: 3
        healthy_threshold: 2
        initializing_timeout: 60000
        reinitializing_timeout: 60000

controller-manager:
    health_check:
        request_line: GET /healthz HTTP/1.0
        port: 10252
        interval: 2000
        response_timeout: 2000
        unhealthy_threshold: 3
        healthy_threshold: 2
        initializing_timeout: 60000
        reinitializing_timeout: 60000

kubectld:
    health_check:
        port: 10240
        interval: 2000
        response_timeout: 2000
        unhealthy_threshold: 3
        healthy_threshold: 2
        initializing_timeout: 60000
        reinitializing_timeout: 60000
