version: '2'

services:
  kubectl-shell:
    labels:
      io.rancher.container.create_agent: "true"
      io.rancher.container.agent.role: environmentAdmin
      io.rancher.k8s.kubectld: "true"
      io.rancher.k8s.token: "true"
      io.rancher.kubernetes.service_account: rancher
    command:
    - kubectl-shell-entry.sh
    image: joshwget/kubectld
    privileged: true
